In [1]:
#------------------------------HEADER------------------------------#
#Projeto computacional em que implementamos o método simplex.
'''AUTHORS:
Daniel Reis, Matheus Alves, Mariane Santana.
'''

import numpy as np
#------------------------------HEADER------------------------------#

In [2]:
linhas = int(input("Informe o tamanho da matriz.\nLinhas: "))
colunas = int(input("\nColunas: "))
# print("i, j = ({:1f}, {:1f})\n".format(linhas, colunas))

A = np.zeros(linhas*colunas, dtype=float).reshape(linhas, colunas)

for i in range(linhas):
    A[i] = input().split()

print(A)

[[10.  2.  1.  1.  0.  0.]
 [ 7.  3.  2.  0.  1.  0.]
 [ 2.  4.  1.  0.  0.  1.]]


In [3]:
# c = input("Informe o vetor dos custos (separados por um espaço): ").split(sep = " ")
custos = [float(c) for c in input("Informe o vetor dos custos (separados por um espaço): ").split(sep = " ")]

print(custos)

[-12.0, -3.0, -1.0, 0.0, 0.0, 0.0]


In [4]:
recursos = [float(b) for b in input("Informe o vetor dos recursos (separados por um espaço): ").split(sep = " ")]

print(recursos)

[100.0, 77.0, 80.0]


In [33]:
# Define partições e os custos básicos e não-básicos
particao_basica = A[:,(linhas-colunas):].copy()
particao_nbasica = A[:,:linhas].copy()
custos_basicos = custos[(linhas-colunas):].copy()
custos_nbasicos = custos[:linhas].copy()

Loop daqui pra baixo

In [46]:
# Calcula a solução básica factível Xb
xb = np.linalg.solve(particao_basica, recursos)
print(xb)

[10.  7. 60.]


In [47]:
valor_atual = np.dot(np.transpose(custos_basicos), xb)
print(valor_atual)

-120.0


In [48]:
# Calcular os custos relativos
lambda_simplex = np.linalg.solve(np.transpose(particao_basica), custos_basicos)
custos_relativos = [(custos_nbasicos[j] - np.dot(np.transpose(lambda_simplex), particao_nbasica[:,j])) for j in range(colunas-linhas)]
custo_relativo_min = min(custos_relativos)
indice_entrada_base = custos_relativos.index(custo_relativo_min)

In [49]:
print(lambda_simplex)
print(custos_relativos)
print(custo_relativo_min)
print(indice_entrada_base)

[-1.2  0.   0. ]
[1.2, -0.6000000000000001, 0.19999999999999996]
-0.6000000000000001
1


In [50]:
# Teste de otimalidade
if (custo_relativo_min >= 0):
    print("Solução atual é ótima.")
    print("Valor ótimo da solução: ", valor_atual)
    print("Variáveis ótimas: ", xb)
else:
    print("Solução atual não é ótima.")
    print("Valor atual da solução: ", valor_atual)
    print("Variáveis: ", xb)

Solução atual não é ótima.
Valor atual da solução:  -120.0
Variáveis:  [10.  7. 60.]


In [51]:
# Cálculo da Direção Simplex
direcao_simplex = np.linalg.solve(particao_basica, particao_nbasica[:,indice_entrada_base])
print(direcao_simplex)

[0.2 1.6 3.6]


In [52]:

if True in (direcao_simplex <= 0):
    print("Problema não tem solução ótima finita.")
else:
    passo = xb/direcao_simplex
    epsilon = min(passo)
    indice_saida_base = np.where(passo == epsilon)[0][0]

In [53]:
print(passo)
print(epsilon)
print(indice_saida_base)

[50.          4.375      16.66666667]
4.375
1


In [42]:
entrada_base = particao_nbasica[:,indice_entrada_base].copy()
saida_base = particao_basica[:,indice_saida_base].copy()
particao_basica[:,indice_saida_base] = entrada_base
particao_nbasica[:,indice_entrada_base] = saida_base

In [43]:
entrada_custo = custos_nbasicos[indice_entrada_base]
saida_custo = custos_basicos[indice_saida_base]
custos_basicos[indice_saida_base] = entrada_custo
custos_nbasicos[indice_entrada_base] = saida_custo

In [44]:
print(particao_basica)
print(particao_nbasica)

[[10.  0.  0.]
 [ 7.  1.  0.]
 [ 2.  0.  1.]]
[[1. 2. 1.]
 [0. 3. 2.]
 [0. 4. 1.]]


In [45]:
print(custos_basicos)
print(custos_nbasicos)

[-12.0, 0.0, 0.0]
[0.0, -3.0, -1.0]
